### ISSUE TITLE
forestplot subgroup variable selection should be more user friendly

### ISSUE THREAD

**Issue by danielinteractive** [insightsengineering/teal.modules.hermes#198]
Problem:
![image](https://user-images.githubusercontent.com/1071227/150329046-968c4279-0b86-4f63-98e1-a3ff55cd44a3.png)

All subgroup variables are shown in the drop-down menu.

To do:

- [x] Rename drop-down to `Select Categorical Subgroup Variable`
- [x] Show only character / factor variables in the drop-down
- [x] Test what happens if there are no character / factor variables

**Comment by AniaGolab** [comment]
Hi Daniel, 
The linked request adds "Categorical" to description. I can also confirm that the variables outputted in the drop-down are only categorical (via categorical=TRUE set-up). I also checked what happens if no categorical variables are present in the mae via SummarizedExperiment::colData(mae)["AGE"] . In such case the application runs correctly and simply outputs no variables to group by (empty list).
Fixes #198
